name: main@workflow_push

on:
  push:
      branches:
        - main

concurrency: 
    group: '${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    build-image:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          environment: [development, staging, production]

      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Step Git pull
          run: |
            git pull origin main

        - name: Step Get Package Version
          run: |
            export VERSION=$(node -p "require('./package.json').version")
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Step Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: '${{ github.actor }}'
            password: '${{ secrets.GITHUB_TOKEN }}'

        - name: 'Extract metadata (tags, labels) for Docker'
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: 'ghcr.io/${{ github.repository }}'
            tags: |
              type=ref,event=branch
              type=semver,pattern={{version}},value=${{ env.VERSION }}-${{ vars.environment }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: '${{ steps.meta.outputs.tags }}'
            labels: '${{ steps.meta.outputs.labels }}'