name: workflow_pull_request

on:
  push:
      branches:
        - main

concurrency: 
    group: '${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    create-tag:
      if: ${{ github.event.pull_request.merged == true}}
      needs: [ pull-request-merged ]
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout do Repositório
          uses: actions/checkout@v3

        - name: Step Get Package Version
          run: |
            export VERSION=$(node -p "require('./package.json').version")
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Step Configure Git
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"

        - name: Step Create Tag from code
          run: |
            git tag -a v${{ env.VERSION }} -m "Creating a tag for main in the version ${{ env.VERSION }} - ${{github.repository}}-${{github.ref}}-${{github.sha}}"
            git push origin v${{ env.VERSION }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}